In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
dataset.head(2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0

Insure data has not null value

In [4]:
dataset.isnull().sum()

CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
input_data = dataset.iloc[:,:-1]
output_data = dataset["Exited"]

Scaling

In [6]:
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data),columns=input_data.columns)

Train Test Split data

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data,train_size=0.25,random_state=10)

In [9]:
x_train.shape

(2500, 8)

***MultiLayer Percepton***

In [10]:
import tensorflow

# *Dropout Layer*

In [11]:
from keras.layers import Dense, Dropout
from keras.regularizers import L2
from keras.callbacks import EarlyStopping

from keras.models import Sequential

In [12]:
ann = Sequential()

In [13]:
ann.add(Dense(6,input_dim = 8,activation="relu",kernel_regularizer = L2(l2=0.01)))
ann.add(Dropout(0.5))
ann.add(Dense(4,activation="relu"))
ann.add(Dropout(0.5))
ann.add(Dense(2,activation="relu"))
ann.add(Dropout(0.5))
ann.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy",metrics=['accuracy'])

In [ ]:
ann.fit(x_train,y_train, batch_size=100, epochs = 50,validation_data=(x_test,y_test),callbacks=EarlyStopping())

Epoch 1/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - accuracy: 0.7328 - loss: 0.8543 - val_accuracy: 0.6173 - val_loss: 0.7747
Epoch 2/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.7284 - loss: 0.8302 - val_accuracy: 0.6659 - val_loss: 0.7362
Epoch 3/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7264 - loss: 0.8066 - val_accuracy: 0.7055 - val_loss: 0.7057
Epoch 4/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7444 - loss: 0.7621 - val_accuracy: 0.7363 - val_loss: 0.6850
Epoch 5/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7504 - loss: 0.7221 - val_accuracy: 0.7583 - val_loss: 0.6678
Epoch 6/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7584 - loss: 0.6962 - val_accuracy: 0.7795 - val_loss: 0.6530
Epoch 7/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7616 - loss: 0.6768 - val_accuracy: 0.7889 - val_loss: 0.6398
Epoch 8/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7768 - loss: 0.6628 - val_accuracy: 0.7935 - val_loss: 0.6290
Epoch 9/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7792 - loss: 0.6505 - val_accuracy: 0.7943 - val_loss: 0.6191
Epoch 10/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7840 - loss: 0.6381 - val_accuracy: 0.7943 - val_loss: 0.6099
Epoch 11/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7904 - loss: 0.6315 - val_accuracy: 0.7943 - val_loss: 0.6010
Epoch 12/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7880 - loss: 0.6207 - val_accuracy: 0.7943 - val_loss: 0.5931
Epoch 13/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7924 - loss: 0.6191 - val_accuracy: 0.7943 - val_loss: 0.5864
Epoch 14/50
 1/25 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8000 - loss: 0.5839

***Handling overfitting using Batch Normalization***

In [ ]:
train_accuracy = ann.history.history["accuracy"]
test_accuracy = ann.history.history["val_accuracy"]

In [ ]:
plt.plot([i for i in range(1,51)],train_accuracy)
plt.plot([i for i in range(1,51)],test_accuracy)
plt.show()

# Identity overfitting

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
prd = ann.predict(x_test)
prd_data = []
for i in prd:
  if i[0] > 0.5 :
    prd_data.append(1)
  else:
    prd_data.append(0)

In [ ]:
accuracy_score(y_test,prd_data)*100

In [ ]:
prd1 = ann.predict(x_train)
prd_data1 = []
for i in prd1:
  if i[0] > 0.5 :
    prd_data1.append(1)
  else:
    prd_data1.append(0)

In [ ]:
accuracy_score(y_train,prd_data1)*100

Hance, our model is overfitted because test score is 79 and train score is 80