In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")

dataset.drop(columns=["User ID","Gender"],inplace=True)

In [3]:
dataset.head(3)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0

value_counts help to find total  no. of each data

In [4]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

whithout Imbalancing data

In [5]:
x = dataset.iloc[:,:-1]
y = dataset["Purchased"]

Train Test Split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.2,random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [10]:
lr.score(x_test,y_test)*100

84.0625

ML predict wrong value because our data is Bayes

In [11]:
lr.predict([[45,26000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

# ***Import imblearn for imbalanced dataset***

## Random Under Sampling

In [12]:
from imblearn.under_sampling import RandomUnderSampler

In [13]:
ru = RandomUnderSampler()
ru_x, ru_y = ru.fit_resample(x,y)

check the data is imbalanced or not

In [14]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(ru_x,ru_y,train_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr1 = LogisticRegression()
lr1.fit(x_train1, y_train1)

LogisticRegression()

In [19]:
lr1.score(x_test1,y_test1)*100

83.4061135371179

In [22]:
lr1.predict([[45,26000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])