In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv("package.csv")

In [6]:
dataset.head(2)

   cgpa  package
0  6.89     3.26
1  5.12     1.98

split data

In [7]:
x = dataset.iloc[:,:-1]
y = dataset["package"]

Train Test Split data

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.25,random_state=42)

# ***Voting And Averaging(Classification)***

In [10]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

***Train ml using LinearRegression***

In [14]:
lr = LinearRegression()
lr.fit(x_train,y_train)
lr.score(x_train,y_train)*100, lr.score(x_test,x_test)

(80.67674147311243, -13.473914558804275)

***Train ml using SVR***

In [12]:
sv = SVR()
sv.fit(x_train,y_train)
sv.score(x_train,y_train)*100, sv.score(x_test,x_test)

(81.07744616549691, -13.287713185023621)

***Train ml using DecisionTreeRegressor***

In [13]:
dt = DecisionTreeRegressor()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)*100, dt.score(x_test,x_test)

(99.07430651949372, -13.53357964541638)

Voting Regressor

In [15]:
from sklearn.ensemble import VotingRegressor

In [16]:
li = [("lr1",LinearRegression()),("dt1",DecisionTreeRegressor()),("sv1",SVR())]

In [39]:
vc = VotingRegressor(li, weights=[30,5,30])
vc.fit(x_train,y_train)

VotingRegressor(estimators=[('lr1', LinearRegression()),
                            ('dt1', DecisionTreeRegressor()), ('sv1', SVR())],
                weights=[30, 5, 30])

In [40]:
vc.score(x_train,y_train)*100, vc.score(x_test,y_test)*100

(83.89583194029754, 76.86004253478352)

check how predict work

In [41]:
prd = {"dt":dt.predict(x_test),"svm":sv.predict(x_test),"lr":lr.predict(x_test),"vc":vc.predict(x_test)}

In [42]:
pd.DataFrame(prd)

       dt       svm        lr        vc
0    3.24  2.855951  2.783327  2.851975
1    2.94  3.125814  3.139417  3.117799
2    3.08  3.185735  3.202594  3.185383
3    2.43  2.423497  2.392778  2.409819
4    4.00  3.590632  3.529966  3.594122
..    ...       ...       ...       ...
145  3.08  3.174274  3.191107  3.174791
146  2.49  2.910223  2.852248  2.851140
147  3.89  3.764694  3.673551  3.732267
148  2.33  2.618209  2.547849  2.563565
149  4.11  3.908381  3.822878  3.884427

[150 rows x 4 columns]